### ISSUE TITLE
Doesn't work after running

### ISSUE THREAD

**Issue by Testacda** [WeaveAche/hanime-auto-coins-collector#1]
I downloaded the respository and tried to run it by "py getcoins.py". I freshly installed python 3.9.6 and it said I did not have requests and dateutil which I installed by from "pip install requests/python-dateutil". After I get this error when I try to run the py file.

```
[*] Logged in as Redacted
[*] Coins count: 0
Traceback (most recent call last):
  File "C:\Users\Dromu\Documents\hanime-auto-coins-collector-main\getcoins.py", line 102, in <module>
    main()
  File "C:\Users\Dromu\Documents\hanime-auto-coins-collector-main\getcoins.py", line 90, in main
    print(f"[*] Last clicked on {parser.parse(info['last_clicked']).ctime()} UTC")
  File "C:\Users\Dromu\AppData\Local\Programs\Python\Python39\lib\site-packages\dateutil\parser\_parser.py", line 1368, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "C:\Users\Dromu\AppData\Local\Programs\Python\Python39\lib\site-packages\dateutil\parser\_parser.py", line 640, in parse
    res, skipped_tokens = self._parse(timestr, **kwargs)
  File "C:\Users\Dromu\AppData\Local\Programs\Python\Python39\lib\site-packages\dateutil\parser\_parser.py", line 719, in _parse
    l = _timelex.split(timestr)         # Splits the timestr into tokens
  File "C:\Users\Dromu\AppData\Local\Programs\Python\Python39\lib\site-packages\dateutil\parser\_parser.py", line 201, in split
    return list(cls(s))
  File "C:\Users\Dromu\AppData\Local\Programs\Python\Python39\lib\site-packages\dateutil\parser\_parser.py", line 69, in __init__
    raise TypeError('Parser must be a string or character stream, not '
TypeError: Parser must be a string or character stream, not NoneType
```

**Comment by WeaveAche** [comment]
This could most probably be happening because you have never clicked on an ad before, if you haven't then click on ad manually once and then run the script after the timeout or you could remove the lines 90-96 from here and then try running. 
![Screenshot from 2021-08-11 19-56-43](https://user-images.githubusercontent.com/74822524/129047343-2f035bb4-2241-466f-a885-80c1504327d5.png)

**Comment by Testacda** [comment]
I clicked an ad and it worked now thanks!
